add doc to create landing page
onmetal/documentation pull request #26
Opened 2021-09-14 07:56 UTC by EvgeniaOrfeeva

Draft version for landing page. Open for discussion

2021-09-14 07:58 UTC, MalteJ commented
Please remove the `docs/.DS_Store` file from your commit :)

2021-09-14 08:07 UTC, afritzler commented
Added `.DS_Store` to `.gitignore`

2021-09-14 08:19 UTC, dmvolod commented on docs/648992860640615517gardener_on_metal_-_intro.md
> +Gardener on Metal is tested on intel and AMD x86_64 processors. Due to its modular architecture Gardener on Metal should be easily portable to ARM (aarch64) or RISC-V processors. This is on our roadm
```suggestion
Gardener on Metal is tested on Intel and AMD x86_64 processors. Due to its modular architecture Gardener on Metal should be easily portable to ARM64 (AArch64) or RISC-V processors. This is on our roadmap but we have not set a deadline, yet.
```

2021-09-14 10:21 UTC, MalteJ commented
> Added `.DS_Store` to `.gitignore`

you still need to remove the file from the commit.

2021-09-14 11:23 UTC, MalteJ approved these changes

2021-09-14 11:24 UTC, MalteJ commented
LGTM

2021-09-14 19:47 UTC, afritzler requested changes
Please rename this file to `index.md` and overwrite the old one.

2021-09-14 19:56 UTC, afritzler commented on docs/648992860640615517gardener_on_metal_-_intro.md
> +> Gardener on Metal is not a new Open Stack.
Do we really want to have this as block quotes? Two consecutive block quotes are violating the Markdown style guide: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md028---blank-line-inside-blockquote

2021-09-15 06:49 UTC, EvgeniaOrfeeva commented on docs/648992860640615517gardener_on_metal_-_intro.md
> +> Gardener on Metal is not a new Open Stack.
Nope, don`t need them at all

2021-09-15 06:51 UTC, MalteJ commented
We probably don't need the bullet points in the Compute / Network / Storage sections. It's not really a list but just different paragraphs. Besides the information is not complete, what a bullet list may imply.

2021-09-15 09:10 UTC, afritzler requested changes
Trailing '.' in headers should not be used in Markdown

2021-09-15 09:10 UTC, afritzler commented on docs/index.md
> +### Gardener on Metal is not a new Open Stack.
```suggestion
### Gardener on Metal is not a new Open Stack
```

2021-09-15 09:10 UTC, afritzler commented on docs/index.md
> +### Gardener on Metal does not support live migration of VMs.
```suggestion
### Gardener on Metal does not support live migration of VMs
```

2021-09-15 09:14 UTC, afritzler commented
Alright, all checks are passing and the content looks also good. I will squash merge this now.

2021-09-15 09:14 UTC, afritzler approved these changes

2021-09-15 09:15 UTC, merged