Add doku for networking of virtualization
onmetal/documentation pull request #27
Opened 2021-09-15 09:23 UTC by hardikdr

@byteocean  Do you want to resolve the conflicts from your branch in this PR, and so that we can add your additions to the main page?
It'll help as we don't have "todo" marks on the main page.

2021-09-15 11:49 UTC, hardikdr commented
Thanks, @byteocean .
Looks like there are some linting errors, that need to be resolved.
I think golint and the extension in vscode should help in finding and resolving them.

2021-09-17 10:42 UTC, afritzler requested changes
Please change the file names and fix the reference in the main `mkdocs.yml` file in the project root.

2021-09-17 10:42 UTC, afritzler commented on docs/components/virtualization/HowToDeploy.md
>  ## At a glance
Can we please use lower case file names? Also I would name it like `installation.md` or `usage.md`.

2021-09-17 10:42 UTC, afritzler commented on docs/components/virtualization/Overview.md
> -
Same here please use lower case file names.

2021-09-17 13:44 UTC, hardikdr commented on docs/components/virtualization/HowToDeploy.md
>  ## At a glance
Sure, that's a good point, done.

2021-09-17 13:44 UTC, hardikdr commented on docs/components/virtualization/Overview.md
> -
done

2021-09-17 14:19 UTC, afritzler approved these changes

2021-09-21 07:20 UTC, afritzler commented
Looks like this can be merged now.

2021-09-21 07:37 UTC, merged